<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign in with Google</name>
   <tag></tag>
   <elementGuidId>31fe5a86-df74-4887-b3be-7f4df7fc2f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='sso_form']/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.body.ripple-effect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32743d74-2eaf-43e1-a5a7-23cf946dced2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>f5979e2d-fa89-4444-adc7-78042f3d8409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>a6225ca09e9c1a</value>
      <webElementGuid>434f0277-d656-47f0-a0fe-8c763489c721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>body ripple-effect</value>
      <webElementGuid>ee042b62-9d8f-433a-bb93-fff55081e9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in with Google</value>
      <webElementGuid>2e95a0f0-7e7c-4b9d-a627-91dfa31f338d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sso_form&quot;)/div[@class=&quot;single_sign_on&quot;]/div[@class=&quot;user_login_options mt-24 db-customscrollbar&quot;]/a[@class=&quot;body ripple-effect&quot;]</value>
      <webElementGuid>1ec2961f-90b7-4c67-a81b-58891037a6e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sso_form']/div/div/a</value>
      <webElementGuid>c2d42961-4be1-46ee-bd24-b630f22d8cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign in with Google')]</value>
      <webElementGuid>a6602478-0277-4e41-9f9b-47703fc7df49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single sign on'])[1]/following::a[1]</value>
      <webElementGuid>94da563b-3523-4158-8792-715b36b274dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powered By'])[1]/preceding::a[2]</value>
      <webElementGuid>55be3345-94a8-4450-80a0-f7c814c5ed79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign in with Google']/parent::*</value>
      <webElementGuid>87517134-442f-4746-8077-234edd407467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>0ee78279-135a-4855-a5d9-ea0d3825622c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/a</value>
      <webElementGuid>f65226bf-a94b-45fc-b811-5ac53fa3fde9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Sign in with Google' or . = 'Sign in with Google')]</value>
      <webElementGuid>a7357e01-a95c-4b44-99ce-f2eb59279883</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
